package com.alejandro.testdeconducir;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import java.io.File;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Alejandro
 */
public class jFramePreguntas extends javax.swing.JFrame {
    private ArrayList<Pregunta> listaPreguntas = new ArrayList<>();
    private static int correctas = 0;
    private static int falsas = 0;
    private int cont = 1;
    private static String resultado = "";
    
    /**
     * Creates new form Preguntas
     */
    public jFramePreguntas() {
        initComponents();        
        txtCorrecta.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        rbtnResp1 = new javax.swing.JRadioButton();
        rbtnResp2 = new javax.swing.JRadioButton();
        rbtnResp3 = new javax.swing.JRadioButton();
        btnAnterior = new javax.swing.JButton();
        btnSiguiente = new javax.swing.JButton();
        txtPregunta = new javax.swing.JLabel();
        txtCorrecta = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setSize(new java.awt.Dimension(50, 50));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Test Clase B: Coches");

        rbtnResp1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnResp1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnResp1ActionPerformed(evt);
            }
        });

        rbtnResp2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnResp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnResp2ActionPerformed(evt);
            }
        });

        rbtnResp3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        rbtnResp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnResp3ActionPerformed(evt);
            }
        });

        btnAnterior.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnAnterior.setText("Anterior");
        btnAnterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAnteriorActionPerformed(evt);
            }
        });

        btnSiguiente.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnSiguiente.setText("Siguiente");
        btnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSiguienteActionPerformed(evt);
            }
        });

        txtPregunta.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        txtPregunta.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                txtPreguntaAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(txtCorrecta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addComponent(txtPregunta, javax.swing.GroupLayout.PREFERRED_SIZE, 926, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(rbtnResp3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rbtnResp2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAnterior)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSiguiente))
                    .addComponent(rbtnResp1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(70, 70, 70))
            .addGroup(layout.createSequentialGroup()
                .addGap(393, 393, 393)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(txtCorrecta, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtPregunta, javax.swing.GroupLayout.DEFAULT_SIZE, 68, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(rbtnResp1)
                .addGap(18, 18, 18)
                .addComponent(rbtnResp2)
                .addGap(18, 18, 18)
                .addComponent(rbtnResp3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAnterior)
                    .addComponent(btnSiguiente))
                .addGap(41, 41, 41))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtPreguntaAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_txtPreguntaAncestorAdded
        getListaPreguntas();
        txtPregunta.setText(listaPreguntas.get(0).getPregunta());
        rbtnResp1.setText(listaPreguntas.get(0).getRespuesta1());
        rbtnResp2.setText(listaPreguntas.get(0).getRespuesta2());
        rbtnResp3.setText(listaPreguntas.get(0).getRespuesta3());
        txtCorrecta.setText(listaPreguntas.get(0).getRespCorrecta());
        
        
    }//GEN-LAST:event_txtPreguntaAncestorAdded

    private void rbtnResp1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnResp1ActionPerformed
        if (rbtnResp1.isSelected()) {
            rbtnResp2.setSelected(false);
            rbtnResp3.setSelected(false);
        }
    }//GEN-LAST:event_rbtnResp1ActionPerformed

    private void rbtnResp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnResp2ActionPerformed
        if (rbtnResp2.isSelected()) {
            rbtnResp1.setSelected(false);
            rbtnResp3.setSelected(false);
        }
    }//GEN-LAST:event_rbtnResp2ActionPerformed

    private void rbtnResp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnResp3ActionPerformed
        if (rbtnResp3.isSelected()) {
            rbtnResp2.setSelected(false);
            rbtnResp1.setSelected(false);
        }
    }//GEN-LAST:event_rbtnResp3ActionPerformed

    private void btnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSiguienteActionPerformed
        
        if(correctas + falsas < 20) {
              if(rbtnResp1.isSelected()) {
                if(rbtnResp1.getText().equals(txtCorrecta.getText())) {
                    correctas++; 
                }              
                else {
                    falsas++;
                }

            }else if(rbtnResp2.isSelected()) {
                if(rbtnResp2.getText().equals(txtCorrecta.getText())) {
                    correctas++; 
                }             
                else {
                    falsas++;
                }           
            }else if(rbtnResp3.isSelected()) {
                if(rbtnResp3.getText().equals(txtCorrecta.getText())) {
                    correctas++;              
                }
                else {
                    falsas++;     
                }       
            }else {       
                falsas++; 
            }

            rbtnResp1.setSelected(false);
            rbtnResp2.setSelected(false);
            rbtnResp3.setSelected(false);
            
            txtPregunta.setText(listaPreguntas.get(cont).getPregunta());
            rbtnResp1.setText(listaPreguntas.get(cont).getRespuesta1());
            rbtnResp2.setText(listaPreguntas.get(cont).getRespuesta2());
            rbtnResp3.setText(listaPreguntas.get(cont).getRespuesta3());
            txtCorrecta.setText(listaPreguntas.get(cont).getRespCorrecta()); 
            cont++;           
        }else {            
            Resultado abrir = new Resultado();
            abrir.setVisible(true);             
            this.dispose();
            cont = 1;
            correctas = 0;
            falsas = 0;

        }   
        
        
        
    }//GEN-LAST:event_btnSiguienteActionPerformed

    private void btnAnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAnteriorActionPerformed
        if(cont >= 0) {
            rbtnResp1.setSelected(false);
            rbtnResp2.setSelected(false);
            rbtnResp3.setSelected(false);
            cont--;
            txtPregunta.setText(listaPreguntas.get(cont).getPregunta());
            rbtnResp1.setText(listaPreguntas.get(cont).getRespuesta1());
            rbtnResp2.setText(listaPreguntas.get(cont).getRespuesta2());
            rbtnResp3.setText(listaPreguntas.get(cont).getRespuesta3());
            txtCorrecta.setText(listaPreguntas.get(cont).getRespCorrecta()); 
               
        }
    }//GEN-LAST:event_btnAnteriorActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jFramePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jFramePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jFramePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jFramePreguntas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jFramePreguntas().setVisible(true);
            }
        });
    }
    
    public void getListaPreguntas(){
        try {
            ObjectMapper mapper = new ObjectMapper();
            
            File file = new File("Preguntas-Respuestas.json");
            final ObjectMapper objectMapper = new ObjectMapper();
            List<Pregunta> preg = objectMapper.readValue(file, new TypeReference<List<Pregunta>>() { });

            preg.forEach(x-> listaPreguntas.add(x));
            Collections.shuffle(this.listaPreguntas);

        } catch (Exception ex) {
            ex.printStackTrace();
        }
    }
    
    public static String getCorrectas() {
        return correctas + "";
    }
    
    public static String getFalsas() {
        return falsas + "";
    }
    
    public static String getResultado() {  
        if (correctas >= 18 && falsas <= 2) {
             resultado = "Aprobado";
        }else {        
             resultado = "Suspenso";
        }
        return resultado;
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAnterior;
    private javax.swing.JButton btnSiguiente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton rbtnResp1;
    private javax.swing.JRadioButton rbtnResp2;
    private javax.swing.JRadioButton rbtnResp3;
    private javax.swing.JLabel txtCorrecta;
    private javax.swing.JLabel txtPregunta;
    // End of variables declaration//GEN-END:variables

    
}
